baseURL = "https://impacthub.github.io/lausanne"
languageCode = "en-us"
title = "ImpactHub Lausanne"
theme = "hugo-icon"
publishDir = "docs"


# Metadata
[params]
  author = "Marc Friederich"
  description = "Nous sommes une communauté locale d’entrepreneurs, un espace coopératif et un laboratoire d’idées, cherchant à apporter des solutions innovantes aux challenges de la société actuelle."

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/impacthublausanne_1.jpg"
  title = "ImpactHub Lausanne"
  teaser = "Rejoignez la plus grande communauté de créatifs et d’entrepreneurs locaux !"
  # description = "Nous sommes une communauté locale d’entrepreneurs, un espace coopératif et un laboratoire d’idées, cherchant à apporter des solutions innovantes aux challenges de la société actuelle."
  contact = "Contactez-nous"

# Navigation section
[params.nav]
  mission = "En résumé"
  services = "Impact Hub Lausanne"
  work = "Événements"
  team = "Équipe"
  contact = "Contact"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = false

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/impacthublausanne_2.jpg"
    # [[params.mission.images.list]]
    #   img = "images/impacthublausanne_3.jpg"
    # [[params.mission.images.list]]
    #   img = "images/impacthublausanne_6.jpg"
    # [[params.mission.images.list]]
    #   img = "images/impacthublausanne_8.jpg"

  [[params.mission.item]]
    weight = 1
    name = "impacthub"
    title = "Impact Hub"
    subtitle = "Au coeur de Lausanne"
    description = "<p>Situé à quelques pas de la place Chauderon, Impact Hub Lausanne met à votre disposition un espace où les entrepreneurs et innovateurs se retrouvent pour prototyper les nouveaux modèles d’une société pour tous - connectant différents secteurs, industries et cultures. Nous vous donnons accès à un espace de travail inspirant, une communauté dynamique et ouverte, des programmes d’incubation de startups, mais aussi des événements dédiés, des cours et des ateliers. En tant que membre, vous rejoignez une communauté de plus 15’000 membres et 80 espaces à travers le monde. </p><ul class='checked'><li>Argument numéro 1</li><li>Argument numéro 2</li><li>Argument numéro 3</li></ul><p><a href='#fh5co-contact' data-nav-section='contact' class='btn btn-primary btn-outline'>Prendre contact</a></p>"

  [[params.mission.item]]
    weight = 2
    name = "services"
    title = "Nos services"
    subtitle = "Avoir un impact, faire la différence"
    description = "<p>Un paragraphe ici qui résume nos services</p><ul class='checked'><li>Abonnements</li><li>Organisation de réunions et d'événements</li><li>Pour les entreprises & organisations</li></ul><p><a href='#fh5co-services' data-nav-section='services' class='btn btn-primary btn-outline'>En apprendre plus sur nos services</a></p>"

  [[params.mission.item]]
    weight = 3
    name = "spaces"
    title = "L'espace"
    subtitle = "Une communauté, un lieu pour accueillir la créativité et l'innovation"
    description = "<p>Notre espace est unique et inspirant, tout ce dont vous avez besoin pour une réflexion créative et une performance optimale. Obtenez votre abonnement mensuel ou louez une de nos salles de réunion à l’heure. Réservez une visite guidée pour devenir membre ou faire un tour de notre espace</p><p><a href='https://davidviale.youcanbook.me/' class='btn btn-primary btn-outline' target='_blank'>Réservez une visite guidée</a></p>"

# Services section
[params.services]
  enable = true
  video = false
  vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "Impact Hub Lausanne"
  description = "<p>Impact Hub Lausanne est le fruit de deux années de recherche et de mise en place d’une structure et d’une communauté répondant aux besoins et mutations liées à l’entrepreneuriat en Suisse romande.</p><p> L’espace collaboratif a pour vocation la mise en relation, le partage de ressources et d’opportunités entre ses membres, la création d’événements et l’incubation de start-ups.</p><p>Comme son nom l’indique, Impact Hub Lausanne tient à avoir un impact, à jouer un rôle de moteur sur le tissu économique local et les marchés en développement, tout en favorisant les projets sociétaux et environnementaux tels que le Lab Vie Durable, premier programme lausannois organisé en partenariat avec le fonds de soutien Engagement Migros.</p>"
  contact = "Prendre contact"

  [[params.services.item]]
    icon = "icon-people"
    photo = "images/impacthublausanne_3.jpg"
    title = "Abonnements"
    description = "Marre d’être isolé dans votre travail ou votre projet? Envie de vous ancrer localement dans votre communauté, de vous inspirer, d’innover, tout en débloquant des opportunités de partenariat? A la recherche d’un lieu dans lequel activités professionnelles, créativité et partage de compétences se rencontrent? Devenez membre du réseau Impact Hub et bénéficiez d’un espace de travail flexible et collaboratif, d’un service Hubonaut dédié, d’une plateforme digitale de communication entres membres et d’événements exclusifs. Votre deuxième chez-vous. "

  [[params.services.item]]
    icon = "icon-speedometer"
    photo = "images/impacthublausanne_4.jpg"
    title = "Organisation de réunions et d'événements"
    description = "Besoin d’une salle fermée pour une réunion, une interview, ou une séance de brainstorming pour quelques heures ou une journée entière? Nous tenons à votre disposition divers services de facilitation (hôte d'accueil, installation audio/vidéo, imprimante laser, scanner, visioconférences…) ainsi que de petite restauration."

  [[params.services.item]]
    icon = "icon-map"
    photo = "images/impacthublausanne_5.jpg"
    title = "Pour les entreprises & organisations"
    description = "Vous souhaitez comprendre les challenges et tendances futures de votre secteur, votre région? Explorer de nouvelles possibilités de développement? Chercher des approches innovantes afin de réaliser des projets tout en vous inscrivant dans une dynamique durable? Afin de faire avancer votre organisation et vos collaborateurs dans cette direction, nous vous accompagnons dans la réalisation de séances de brainstormings et organisation de Hackathons"

  # [[params.services.item]]
  #   icon = "icon-pencil"
  #   title = "Copyrighting"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #
  # [[params.services.item]]
  #   icon = "icon-rocket"
  #   title = "Load Fast"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #
  # [[params.services.item]]
  #   icon = "icon-support"
  #   title = "Customer Support"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

# Location section
[params.location]
  enable = true
  title = "Comment nous trouver"
  description = "<p>Impact Hub Lausanne <br/>Rue du Jura 11 <br/>CH - 1004 Lausanne </p><p>Lundi - Vendredi 09:00 - 19:00</p>"
  map = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2745.126984806966!2d6.621926315969944!3d46.52538897912782!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x478c2e28dd3c3b7b%3A0xe63af32d75408e0b!2sImpact+Hub+Lausanne!5e0!3m2!1sen!2sch!4v1508223202322"

# Work section
[params.work]
  enable = true
  title = "Nos événements"
  description = "Pour rester au courant de nos prochains évenements, rendez-vous sur notre [page facebook](https://www.facebook.com/impacthublausanne/)"
  #
   [[params.work.item]]
     title = "Food Save Challenge"
     subtitle = "Ideation workshop"
     img = "images/impacthublausanne_2.jpg"

   [[params.work.item]]
     title = "Consectetur adipisicing"
     subtitle = "Web Design"
     img = "images/impacthublausanne_7.jpg"

   [[params.work.item]]
     title = "Consectetur adipisicing"
     subtitle = "Web Design"
     img = "images/impacthublausanne_6.jpg"

   [[params.work.item]]
     title = "Consectetur adipisicing"
     subtitle = "Web Design"
     img = "images/impacthublausanne_8.jpg"

  # [[params.work.item]]
  #   title = "Consectetur adipisicing"
  #   subtitle = "Web Design"
  #   img = "images/img_3.jpg"
  #
  # [[params.work.item]]
  #   title = "Consectetur adipisicing"
  #   subtitle = "Web Design"
  #   img = "images/img_2.jpg"
  #
  # [[params.work.item]]
  #   title = "Consectetur adipisicing"
  #   subtitle = "Web Design"
  #   img = "images/img_3.jpg"
  #
  # [[params.work.item]]
  #   title = "Consectetur adipisicing"
  #   subtitle = "Web Design"
  #   img = "images/img_4.jpg"

# # Team section
[params.team]
  enable = true
  title = "L'équipe"
  description = "Il me manque le texte ....."

  [[params.team.item]]
    name = "Bautista"
    position = "Co-founder"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/baut.jpg"
    linkedin = "https://www.linkedin.com/in/bautistad/"
    email = "mailto:bautista.dahl-rocha@impacthub.ch"

  [[params.team.item]]
    name = "David"
    position = "Community and event coordinator"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/PicDV.png"
    email = "mailto:david.viale@impacthub.ch"
    linkedin = "https://www.linkedin.com/in/dviale/"

  [[params.team.item]]
    name = "Alberto"
    position = "Co-founder"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/alberto.png"
    twitter = "https://twitter.com/kidvaldez"
    linkedin = "https://www.linkedin.com/in/albertobyas/"
    email = "mailto:alberto.gomez@impacthub.ch"

  [[params.team.item]]
    name = "Marc"
    position = "Co-founder"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/mfh_2.png"
    email = "mailto:marc.friederich@impacthub.ch"
    twitter = "https://twitter.com/zufrieden"
    linkedin = "https://www.linkedin.com/in/marcfriederich/"
    github = "https://github.com/zufrieden"

  [[params.team.item]]
    name = " Alexandra ‘Santu’ Boëthius"
    position = "Co-Founder - Head of Strategy "
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/santu.jpg"
    email = "mailto:alexandra.boethius@impacthub.net"

  [[params.team.item]]
    name = "Amanda Byrde"
    position = "Co-Founder - Head of Finance "
    img = "images/amanda.jpg"
    email = "mailto:amanda.byrde@impacthub.ch"

  [[params.team.item]]
    name = "Felix Stähli"
    position = "Co-Founder - Head of Operations "
    img = "images/felix.jpg"
    email = "mailto:felix.staehli@impacthub.ch"

  [[params.team.item]]
    name = "Julien Clivaz"
    position = "Co-Founder - Head of Development "
    img = "images/julien.jpg"
    email = "mailto:julien.clivaz@impacthub.net"

  [[params.team.item]]
    name = "Ashleigh Armstrong"
    position = "Community Coordinator "
    img = "images/ashleigh.jpg"
    email = "mailto:ashleigh.armstrong@impacthub.ch"

  [[params.team.item]]
    name = "Erica Mazerolle"
    position = "Program Manager - Sustainable Living Lab "
    img = "images/erica.jpg"
    email = "mailto:erica.mazerolle@impacthub.ch"

  [[params.team.item]]
    name = "Krista Kaufmann"
    position = "-"
    img = "images/krista.png"
    email = "mailto:krista.kaufmann@impacthub.ch"

  [[params.team.item]]
    name = "Enrique Hablutzel"
    position = "Business Development "
    img = "images/enrique.jpg"
    email = "mailto:enrique.hablutzel@impacthub.ch"
    #
    # [[params.team.item]]
    #   name = "Alice Doe"
    #   position = "Chief overlord"
    #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    #   img = "images/person2.jpg"
    #   facebook = "#"
    #   twitter = "#"
    #   instagram = "#"
    #   github = "#"
    #
    # [[params.team.item]]
    #   name = "John Doe"
    #   position = "Chief haranguer"
    #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    #   img = "images/person3.jpg"
    #   facebook = "#"
    #   twitter = "#"
    #   instagram = "#"
    #   github = "#"

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   facebook = "#"
  #   twitter = "#"
  #   instagram = "#"
  #   github = "#"

# Contact section
[params.contact]
  enable = true
  title = "Nous contacter"
  # message = "Notre équipe est toujours là pour répondre à vos questions, que ce soit pour un complément d'information concernant les abonnements, une demande de location ou de partenariat ou encore une demande de rendez-vous sur place. Contactez nous par téléphone ou email."
  message = "Notre équipe est toujours là pour répondre à vos questions, que ce soit pour un complément d'information concernant les abonnements, une demande de location ou de partenariat ou encore une demande de rendez-vous sur place. Contactez nous par téléphone ou email."
  visitlink = "https://davidviale.youcanbook.me/"
  contactvisit = "Réservez une visite guidée"
  emaillink = "mailto:david.viale@impacthub.ch"
  contactemail = "david.viale@impacthub.ch"
  phonelink = "tel:+41793892288"
  contactphone = "+41 (0)79 389 22 88"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = false
  note = "<p><small>&copy; 2016 Free HTML5 Template. All Rights Reserved. <br> Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> Demo Images: <a href='http://pexels.com/' target='_blank'>Pexels</a><br>Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a></small></p>"
  github = "#"
  twitter = "#"
  facebook = "https://www.facebook.com/impacthublausanne/"
  vine = "#"
  linkedin = "#"
  instagram = "#"
